### ISSUE TITLE
Admin Finder Work So Slow

### ISSUE THREAD

**Issue by aligoren** [aligoren/info#1]
I need to find some alternative techniques to speed up.

[m_admin_finder.py](https://github.com/aligoren/info/blob/master/modules/m_admin_finder.py)

**Comment by emregeldegul** [comment]
https://github.com/aligoren/info/pull/3

Bir önceki halinde admin panelini bulsa dahi aramaya devam ediyordu, bu şekilde yapınca paneli bulur bulmaz geri döndü. Biraz daha hız kazandı. Başka önerin var mı?

**Comment by aligoren** [comment]
@MuReCoder Kontrol edecegim. Farkli bir yontem olabilir mi diye ama hiz dogru calisma ile birlikte her zaman tercih sebebi :D

**Comment by ghost** [comment]
Neden sadece main thread üzerinden çalıştırıyorsunuz modülü?

**Comment by aligoren** [comment]
@l0x6c Aslinda ekstra bir yontem olsa cok guzel olurdu. Sanirim bendeki yasanan sorun da bahsettiginiz nedenden oturu. Bunun icin en uygun cozum yontemi ne olmalidir?

**Comment by ghost** [comment]
Panel listesini fonksiyona verilen thread sayısına bölüp hızlandırmayı deneyebiliriz, pek farklı bir çözüm yok gibi. Bunun dışında bağlantı hızı için yapabileceğimiz şey, bir HEAD request atmamız, tüm sayfaya ihtiyacımız yok, var olup olmadığını bilmek yeterli diye düşünüyorum. @MuReCoder @aligoren

**Comment by aligoren** [comment]
@l0x6c Anladim tek basina head request yeterli olur mu peki?

Ben, sirkette bir projede admin panel'e bilincli olarak 404 veriyorum. Ama crawler programlar algiliyor hala. Bu nasil oluyordur acaba.

**Comment by ghost** [comment]
Bence hızlandırmak için iyi bir yol, denediğiniz yazılımları atabilir misiniz? Belki kaynak kodlarından nasıl çalıştıklarına dair bir şeyler çıkarabiliriz.

**Comment by aligoren** [comment]
@l0x6c 

Ben ozellikle sunu denedim

https://github.com/AppoPro/Admin-Control-Panel-Finder

bir de suradaki var

https://github.com/mIcHyAmRaNe/okadminfinder3

Son olarak sunu kullanmistim. Tabii bu biraz degismis gibi. Bu kadar buyuk bi code yapisi yoktu.

https://github.com/Ekultek/Zeus-Scanner

**Comment by ghost** [comment]
@aligoren 

İkinci projeyi inceledim, çok basit bir çalışma mantığı var ve sayfa 404 döndürünce geçmeye ayarlanmış.

```python
(...)
    def checkUrl(self, url, proxies):
        """
        Check target url for HTTPerrors. If Error -> False, If Not Errors-> True
        :param url: string
        :return: boolean
        """

        try:

            # Timeout before check url
            time.sleep(self.timeout)

            # Get connection to target and raise exception if have errors
            req = requests.get('http://' + url, headers=self.header, proxies=proxies)
            req.raise_for_status()
            return True

        except requests.RequestException:
            return False
(...)
```

Bu da bir örnek: 

```python
In [3]: checkUrl('httpbin.org/status/200')
Out[3]: True

In [4]: checkUrl('httpbin.org/status/404')
Out[4]: False

In [5]: 
```

İlk proje de anladığım kadarıyla, sayfada bazı şeyler arıyor.(?)
