### ISSUE TITLE
Port Taramaları NMAP tarafından yapılmalı.

### ISSUE THREAD

**Issue by emregeldegul** [aligoren/info#5]
NAMP geniş ve hızlı bir modül, Manuel taramalar oldukça yavaş, port taramaları nmap tarafından yapılmalı. Daha geniş açıklama sunar.

**Comment by aligoren** [comment]
direkt bir API sunuyor mu? Dusundum ama bagimliliga sahip olsun istememistim ilk anda.

**Comment by emregeldegul** [comment]
Evet. Oldukça da kaliteli bir modül. İstersen ekleyelim, yada farklı
seçenekler üstüne yoğunlaşalım.

https://emregeldegul.net/2017/12/python-nmap-kutuphanesi/

21 Ağu 2018 Sal 19:15 tarihinde Ali GOREN <notifications@github.com> şunu
yazdı:

**Comment by aligoren** [comment]
Olur ekleyebilirsen guzel olur. Bence bu modul de olsun ama bir yontem bulursak daha iyi olur. Mesela modul yuklu degilse bizim standart yavas yapiyi kullandiralim?

**Comment by emregeldegul** [comment]
Tamamdır hallediyorum

**Comment by aligoren** [comment]
Tamam bu arada sana direkt collobarator yetkisi verdim. Yani push ettigin anda direkt yayina alabiliyor olmalisin.
